export const SET_AUTO_LOGIN_TYPE = "SET_AUTO_LOGIN_TYPE";

export const SET_LOGOUT_TYPE = "SET_LOGOUT_TYPE";

export const SET_AUTH_TYPE = "SET_AUTH_TYPE";

export const SET_ACTIVE_APPOINTMENTS = "SET_ACTIVE_APPOINTMENTS";

export const SET_PENDING_APPOINTMENTS = "SET_PENDING_APPOINTMENTS";
